### ISSUE TITLE
support synchronous loading

### ISSUE THREAD

**Issue by dodekeract** [arjanfrans/node-multiconfig#10]
Config files are often loaded only once, when the program starts and therefore don't really block any events. It is more simple to just load them synchronously. If it doesn't require a huge change in your code, I'd suggest this as a "low-priority"-enhancement.
Off topic: nice work, was looking for something like this as I always accidentally commit my config files. :confused:

**Comment by arjanfrans** [comment]
This should be easy to do! I will take a look at it soon. Thanks!

**Comment by arjanfrans** [comment]
I changed to entire thing to do synchronous loading.

**Comment by dodekeract** [comment]
Yeah, I personally prefer synchronous for config files, but I still think it is important to keep both APIs. Just do it like node does for most stuff ````.load()```` and ````.loadSync````.
