### ISSUE TITLE
index config files

### ISSUE THREAD

**Issue by dodekeract** [arjanfrans/node-multiconfig#11]
I'm not sure if I'm missing something, but is it possible, that it's currently quite hard to generate a config file which consists of some huge sub-objects and some really small ones?

Example:
````javascript
{
	hugeDatabaseConfig: {/* ... */},
	hugeSessionConfig: {/* ... */},
	aSingleString: 'example',
	anotherSingleString: 'example',
	/* repeat multiple times */
}
````

As far as I understand that would be possible to implement either using one huge config.json file, or a single config file for:
**A)** The huge sub-objects, which actually benefit from being split up and
**B)** The small sub-objects consisting of a single string, which would only be confusing to have as single files.

I'm unsure, if there is a huge use-case for stuff like that, but I can definitely see this being an improvement for some corner-cases.

I would suggest solving this by allowing an ````index.extension```` file, which will be the base for the config tree of a directory. As somebody might want to use ````index.extension```` for some task related to indexing I think it might also be appropriate to add a new option.

**Comment by arjanfrans** [comment]
What this module does is read all files in the `config` directory and merge it into one Javascript object. If I understand correctly; you see a problem if the object gets too large? The benefit of an index file would be that it can look up deeply nested values fast?

**Comment by dodekeract** [comment]
No, I mean something similar to the famous ````index.html```` or ````index.js````. A file, which can add to the current directory.

### The approach for the example I gave you would **currently** lead to the following file structure:
    config
    ├──hugeDatabaseConfig
    │   └── some-data.json
    ├──hugeSessionConfig
    │   └── some-data.json
    ├──a-single-string.json
    └──another-single-string.json
    (multiple other small sub-objects would be in the same directory)

### I'm suggesting that it could support this:
    config
    ├── hugeDatabaseConfig
    │    └── some-data.json
    ├── hugeSessionConfig
    │    └── some-data.json
    └── index.json
where ````index.json```` contains the information of both ````aSingleString```` and ````anotherSingleString````

**Comment by arjanfrans** [comment]
Now I understand! That is a good idea. I thought about this before, but kinda forgot about it. This would be a nice feature to implement.

**Comment by arjanfrans** [comment]
Implemented: https://github.com/arjanfrans/node-multiconfig/commit/b0ba5a076de181aef06cd5f06149e30d80b66401
