### ISSUE TITLE
Support variations of a config file

### ISSUE THREAD

**Issue by arjanfrans** [arjanfrans/node-multiconfig#8]
example-config-1.json
example-config-2.json

**Comment by ArjanFrans** [comment]
Also support directories.

**Comment by dodekeract** [comment]
Also make ````example-config.json```` equivalent to ````example-config-0.json````, so that it still looks nice on github if ````*-1.json```` files are .gitignored.

**Comment by arjanfrans** [comment]
I implemented this, it seems to work. See https://github.com/arjanfrans/node-multiconfig/commit/2ff01e2447979a215936e5227651087e6ea3ea51

Code needs some cleanup and doc blocks, it is becoming a confusing mess.
